name: bloom_mobile
description: eCommerce app

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  collection: ^1.15.0
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  logger: ^1.1.0
  retrofit: ^3.0.1+1
  synchronized: ^3.0.0+2

  common_widgets:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_widgets
  common_models:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_models
  common_network_components:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_network_components
  common_utilities:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_utilities
  static_i18n:
    git:
      url: https://github.com/kume1a/flutter_static_i18n.git
  global_navigator:
    git:
      url: https://github.com/kume1a/flutter_global_navigator.git

dev_dependencies: 
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.6
  freezed: ^2.0.3
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  lint: ^1.8.2
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/icons/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo_ios.png"
  image_path_ios: "assets/images/logo_ios.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffffff"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo_550.png
  #  color_dark: "#042a49"
  #  image_dark: assets/images/logo_550_dark.pngw
  fullscreen: true
  android12: false
